resolver: lts-14.27 # Last 8.6.5
compiler: ghc-8.6.4

# resolver: lts-6.13

# flags: {}

packages:
 - src/lvish/
 - src/par-classes/
 - src/par-collections/
 - src/par-collections/tests/
 - src/par-mergesort/
 - src/par-transformers/
 - deps/concurrent-skiplist/
 - deps/ctrie

 # - location:
 #    git:  https://github.com/iu-parfunc/tslogger.git
 #    commit: bfa8d2b52f0d41439863b15863baa0ca2ef613d9
    
# TODO: Revive:
 # - haskell/lvish-apps/
 # - haskell/lvish-apps/cfa/
 # - haskell/lvish-apps/pbbs/
# - haskell/lvish-graph-algorithms/
 # - haskell/fhpc13-lvars/
 # - haskell/fhpc13-lvars/benchmarks/bf-traverse-LVar/
 # - haskell/fhpc13-lvars/benchmarks/bf-traverse-monad-par/
 # - haskell/fhpc13-lvars/benchmarks/bf-traverse-Strategies/

# TODO: Add:
# haskell/par-schedulers
 
extra-deps:
 - vector-0.12.1.2
 - tslogger-0.1.0.1
 - atomic-primops-0.8.4
 - chaselev-deque-0.5.0.5
 - bits-atomic-0.1.3
 - thread-local-storage-0.1.0.3
 - pcg-random-0.1.3.4
